"""Aggregate both products' results into the public top-level README (Layer-1 render).

This is the file-writer companion to render.py's per-product `render_product`. It reads
each product's schema-validated `results/latest.json`, renders its closed-schema table,
and writes the ENTIRE top-level README.md from a fixed preamble constant + the generated
tables. The README is 100%-generated by construction: there is no hand-edited region a
reviewer could later slip free-text into, so the closed-schema guard (render.py) is the
only path from harness output to the public page.

Invoked by the auto-refresh Action (#3866) as `python3 -m render.generate` from the repo
root, and runnable directly as `python3 render/generate.py`.

Import note: under `-m render.generate` the `render/` DIRECTORY is bound as a namespace
package named `render`, which shadows `render.py` — so a flat `from render import ...`
resolves to the directory (no `render_product` attribute) and fails. We therefore load
render.py by explicit file path via importlib, which is invariant across all invocations
(`-m render.generate`, `python3 render/generate.py`, `cd render && python3 generate.py`)
and needs no `__init__.py` (which would break the dependency-free direct-run tests). The
sys.path insert still puts render/ first so render.py's own flat `from schema import ...`
resolves.
"""

import importlib.util
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)


def _load_render():
    spec = importlib.util.spec_from_file_location("_bench_render", os.path.join(_HERE, "render.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return (
        mod.render_matrix,
        mod.render_north_star,
        mod.render_operating_envelope,
        mod.render_what_this_means,
        mod.render_burst_corroboration,
        mod.render_warm_bind_decomposition,
        mod.render_cold_bind_decomposition,
        mod.render_warm_vs_cold,
        mod.render_scale_proof,
        mod.render_cluster_scale,
        mod.render_stepup,
        mod.render_kata_activation,
        mod.render_concurrent_burst,
        mod.render_warm_pool_acquisition,
        mod.render_at_scale_contention,
        mod.render_cluster_saturation,
        mod.render_provisioning_rate_sweep,
        mod.render_session_turnover,
        mod.render_suspend_latency,
        mod.render_density_detail,
        mod.render_vcpu_footprint,
        mod.render_recipe,
    )


(render_matrix, render_north_star, render_operating_envelope, render_what_this_means,
 render_burst_corroboration, render_warm_bind_decomposition, render_cold_bind_decomposition,
 render_warm_vs_cold, render_scale_proof, render_cluster_scale, render_stepup,
 render_kata_activation, render_concurrent_burst, render_warm_pool_acquisition,
 render_at_scale_contention, render_cluster_saturation, render_provisioning_rate_sweep,
 render_session_turnover, render_suspend_latency, render_density_detail, render_vcpu_footprint,
 render_recipe) = _load_render()

# Product -> results path, relative to the repo root (parent of render/).
# The PUBLIC customer page is SANDBOX-ONLY (alex 2026-06-28): substrate demotes from a
# co-equal published table to an INTERNAL data-engine — its harness + schema-validated
# results/latest.json stay in-tree (and the cross-contract guard still validates the
# substrate emitter↔render contract against them), but they are NOT rendered to the
# public README. Re-adding the substrate tuple here is the single switch to re-publish it.
_PRODUCTS = (
    ("sandbox", "sandbox/results/latest.json"),
)

# Optional companion artifact for the sandbox matrix: the sandbox-kata product's results,
# measured in a SEPARATE run on the kata node pool (`run --product sandbox-kata` writes its
# own latest.json by construction — harness/scenario_map.py — so it can never overwrite the
# gVisor artifact). When present it fills the Kata + microVM rows of the ONE sandbox matrix
# via render_matrix(results, kata_results=...); it is deliberately NOT a _PRODUCTS entry —
# that would render a duplicate full matrix + conditional blocks instead of merging rows.
# Absent file ⇒ kata rows render pending (graceful degradation, README unchanged).
_KATA_RESULTS_REL = "sandbox-kata/results/latest.json"

# Fixed, reviewed-once customer preamble. No measured numbers here — every number on the
# page comes from render_product, so this constant carries zero PII risk.
_PREAMBLE = """\
# Honest benchmarks — GKE agent sandbox

**How fast can your agent get a sandbox that has actually run its first instruction?** That is the
only question this page answers. The metric is **TTFE (Time-To-First-Instruction)** — the wall-clock
from "create this sandbox" to "it ran my first instruction and returned a result." Not pod-Ready (a
pod can look ready seconds before it can run your code) — the real wait.

**North Star:** a warm sandbox with **TTFE p95 under 0.5s** — the bar the scorecard below grades
against. The **scale target** is to hold **sub-1s at 300+ creations/sec**, on a stock GKE cluster
you can provision yourself.

Two runtimes, two isolation trade-offs:
- **gVisor** — a user-space kernel intercepting syscalls; near-container speed, strong isolation.
- **Kata** — each sandbox in its own tiny VM; hardware-grade isolation, higher activation cost.

Every number below is **machine-rendered from a real harness run and reproducible** — no cell is
typed by hand, and each is a **floor, not a ceiling** (what a *vanilla* OSS build delivers today;
a bigger pool or denser nodes should beat it). Reproduce the whole page in four commands:

```bash
kind create cluster                                # 0. portable path — a free local cluster
bash recipe/install-controller-from-main.sh        # 1. the OSS controller, built from upstream main
python3 -m harness.run                             # 2. run the suite -> sandbox/results/latest.json
python3 -m render.generate && git diff README.md   # 3. re-render this page + diff the result
```

First run `pip install -r harness/requirements.txt`; the gVisor/Kata rows need a matching GKE node
pool — full recipe in [`recipe/REPRODUCE.md`](recipe/REPRODUCE.md), deep-dive tables in
[DETAILS.md](DETAILS.md).
"""

# Deep-dive appendix header. Same no-measured-numbers-here rule as _PREAMBLE: every
# number in DETAILS.md comes from a render function, so this constant carries zero PII risk.
_DETAILS_PREAMBLE = """\
# Honest benchmarks — deep-dive appendix

The corroboration and decomposition tables behind the headline page
([README.md](README.md)). Same rule: **every number is machine-rendered from a real
harness run — nothing here is typed by hand.** Start with the headline page; come here
when you want to see the working.
"""


def _repo_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build_readme(root=None):
    """Return the full README text: preamble + 9-col Core Metrics matrix + TTFE corroboration + warm-vs-cold + Scale Proof.

    For each present product we render the closed-schema Core Metrics matrix (render_matrix),
    then — when the #3954 burst-create exec fields are present — the TTFE Corroboration block
    (render_burst_corroboration; INERT/omitted otherwise), then — when a warm_vs_cold object is
    present — the Warm-vs-Cold Speedup block (render_warm_vs_cold; INERT/omitted otherwise), and,
    when a scale_proof object is present, the Scale Proof (Linearity Check) table.
    """
    root = root or _repo_root()
    kata_results = None
    kata_path = os.path.join(root, _KATA_RESULTS_REL)
    if os.path.exists(kata_path):
        with open(kata_path) as fh:
            kata_results = json.load(fh)
    sections = [_PREAMBLE.rstrip()]
    for product, rel in _PRODUCTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            results = json.load(fh)
        kr = kata_results if product == "sandbox" else None
        sections.append(render_matrix(results, kata_results=kr).rstrip())
        # hb#134 H2-fold: the reader-facing interpretation is ONE top-level block. The
        # plain-English "What this means for you" synthesis leads, then the two supporting
        # scorecards fold UNDER it as `###` sub-blocks — "what wait should I budget?" (operating
        # envelope) and "how close to the North Star?" (the p95-vs-bar scorecard). This collapses
        # three former H2s into one, so the page skims as: matrix → what-it-means → does-it-scale.
        sections.append(render_what_this_means(results).rstrip())
        sections.append(render_operating_envelope(
            results, heading="### What wait should I budget?").rstrip())
        # #4162 Option A: North-Star scorecard — render-derived from the matrix's measured
        # warm-hit p95 (zero emit-key change; the locked schema contract untouched).
        north_star = render_north_star(
            results, kata_results=kr, heading="### How close to the North Star?")
        if north_star.strip():
            sections.append(north_star.rstrip())
        # hb#134: Scale-Proof + Concurrent-Burst + Saturation + at-scale Contention merge into ONE
        # user-facing "Does it hold at cluster scale?" section (render_cluster_scale demotes each
        # to a ### sub-block, including the honest over-subscription retraction as the 4th).
        cluster_scale = render_cluster_scale(results)
        if cluster_scale.strip():
            sections.append(cluster_scale.rstrip())
        stepup = render_stepup(results)  # INERT today; standalone ## when a stepup object emits
        if stepup.strip():
            sections.append(stepup.rstrip())
    # #4021: the Reproducibility Recipe is product-agnostic architecture prose, so it renders
    # ONCE after the per-product loop — the preamble forward-refs "the recipe at the bottom".
    sections.append(render_recipe().rstrip())
    return "\n\n".join(sections) + "\n"


def build_details(root=None):
    """Return the deep-dive appendix (DETAILS.md): corroboration + decomposition tables.

    hb#134 page-friendliness split: the headline README carries the answer a non-infra
    reader needs (matrix + operating envelope + scale + burst); the working behind those
    numbers — burst-create corroboration, the bind-vs-exec decomposition (warm + cold),
    the full warm-vs-cold leg table (only its punchline stays on the headline page),
    the Kata pod-Ready table, the warm-pool acquisition breakdown, and the per-runtime
    Max-Density table (relocated off the headline matrix in the same pass) — moves here so
    the front page stays scannable. Same closed-schema render path as build_readme: each
    block is INERT (returns "") unless its required fields are present, so DETAILS degrades
    to an honest skeleton rather than a blank or a guess.
    """
    root = root or _repo_root()
    kata_results = None
    kata_path = os.path.join(root, _KATA_RESULTS_REL)
    if os.path.exists(kata_path):
        with open(kata_path) as fh:
            kata_results = json.load(fh)
    sections = [_DETAILS_PREAMBLE.rstrip()]
    for product, rel in _PRODUCTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            results = json.load(fh)
        for renderer in (
            render_burst_corroboration,
            render_warm_bind_decomposition,
            render_cold_bind_decomposition,
            render_warm_vs_cold,
            render_kata_activation,
            render_warm_pool_acquisition,
        ):
            block = renderer(results)
            if block.strip():
                sections.append(block.rstrip())
        # Max-Density relocated here from the headline matrix (hb#134). kata_results fills
        # the kata-microvm row when its separate run is present, mirroring build_readme.
        kr = kata_results if product == "sandbox" else None
        density = render_density_detail(results, kata_results=kr)
        if density.strip():
            sections.append(density.rstrip())
        # #3868: per-sandbox declared footprint — the reproducibility qualifier for Max Density
        # (gVisor's tiny request vs Kata's guest-sane microVM floor differ ~50x, so densities are
        # only comparable with the footprint stated). Placed next to density; same kata_results
        # source. INERT-first: renders nothing until a fire emits the provenance footprint fields.
        footprint = render_vcpu_footprint(results, kata_results=kr)
        if footprint.strip():
            sections.append(footprint.rstrip())
        # hb#134: the honest-limits RETRACTION posture stays on the headline page; only the full
        # bind/exec decomposition table + non-comparable caveat move here (detail=True).
        contention_detail = render_at_scale_contention(results, detail=True)
        if contention_detail.strip():
            sections.append(contention_detail.rstrip())
        # hb#132: the cluster-saturation ceiling keeps its headline posture on the front page (the
        # third render_cluster_scale sub-block); only the full per-node/per-cluster + bind/exec
        # decomposition table moves here (detail=True), mirroring the at_scale_contention split.
        saturation_detail = render_cluster_saturation(results, detail=True)
        if saturation_detail.strip():
            sections.append(saturation_detail.rstrip())
        # #4086: provisioning-rate ceiling — a THIRD distinct axis (offered reconcile rate vs
        # ready-convergence), not folded into the step-up Pareto or at_scale_contention.
        # DETAILS-only for now; headline promotion tracked as a follow-up.
        rate_sweep = render_provisioning_rate_sweep(results)
        if rate_sweep.strip():
            sections.append(rate_sweep.rstrip())
        # #3868: warm-pool session-turnover refill latency — the RECLAIM side of the agentic
        # lifecycle (the matrix + warm_pool_acquisition measure the claim side). INERT-first:
        # renders nothing until a session_turnover fire emits a measured refill median. DETAILS-only
        # for now; headline promotion tracked as a follow-up (mirrors render_provisioning_rate_sweep).
        turnover = render_session_turnover(results)
        if turnover.strip():
            sections.append(turnover.rstrip())
        # #3868: administrative-suspend latency — the cost-lever response time for reclaiming a
        # sandbox's compute (operatingMode=Suspended patch -> terminal Suspended). Carries a static
        # capability note that upstream has NO idle/auto-suspend (operatingMode is Running;Suspended
        # only). INERT-first: renders nothing until a suspend_resume fire emits a measured suspend
        # median. DETAILS-only for now; headline promotion tracked as a follow-up.
        suspend = render_suspend_latency(results)
        if suspend.strip():
            sections.append(suspend.rstrip())
    return "\n\n".join(sections) + "\n"


def main(argv=None):
    root = _repo_root()
    readme = build_readme(root)
    out = os.path.join(root, "README.md")
    with open(out, "w") as fh:
        fh.write(readme)
    sys.stderr.write(f"generate: wrote {out} ({len(readme)} bytes)\n")
    details = build_details(root)
    details_out = os.path.join(root, "DETAILS.md")
    with open(details_out, "w") as fh:
        fh.write(details)
    sys.stderr.write(f"generate: wrote {details_out} ({len(details)} bytes)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
