"""Aggregate both products' results into the public top-level README (Layer-1 render).

This is the file-writer companion to render.py's per-product `render_product`. It reads
each product's schema-validated `results/latest.json`, renders its closed-schema table,
and writes the ENTIRE top-level README.md from a fixed preamble constant + the generated
tables. The README is 100%-generated by construction: there is no hand-edited region a
reviewer could later slip free-text into, so the closed-schema guard (render.py) is the
only path from harness output to the public page.

Invoked by the auto-refresh Action (#3866) as `python3 -m render.generate` from the repo
root, and runnable directly as `python3 render/generate.py`.

Import note: under `-m render.generate` the `render/` DIRECTORY is bound as a namespace
package named `render`, which shadows `render.py` — so a flat `from render import ...`
resolves to the directory (no `render_product` attribute) and fails. We therefore load
render.py by explicit file path via importlib, which is invariant across all invocations
(`-m render.generate`, `python3 render/generate.py`, `cd render && python3 generate.py`)
and needs no `__init__.py` (which would break the dependency-free direct-run tests). The
sys.path insert still puts render/ first so render.py's own flat `from schema import ...`
resolves.
"""

import glob
import importlib.util
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

# wip.py is a static, data-free module (the closed pending-reason catalog + WORK_IN_PROGRESS.md
# generator, hb#166). It flat-imports via the sys.path insert above, same as render.py's own
# `from schema import ...` — no importlib dance needed (it has no `render` shadowing concern).
from wip import build_work_in_progress  # noqa: E402


def _load_render():
    spec = importlib.util.spec_from_file_location("_bench_render", os.path.join(_HERE, "render.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return (
        mod.render_matrix,
        mod.render_core_metrics_legend,
        mod.render_north_star_caption,
        mod.render_known_anomalies_table,
        mod.render_known_anomalies_detail,
        mod.render_operating_envelope,
        mod.render_what_this_means,
        mod.render_burst_corroboration,
        mod.render_warm_bind_decomposition,
        mod.render_bind_exec_pie,
        mod.render_cold_bind_decomposition,
        mod.render_warm_vs_cold,
        mod.render_scale_proof,
        mod.render_cluster_scale,
        mod.render_stepup,
        mod.render_cost_methodology,
        mod.render_kata_activation,
        mod.render_concurrent_burst,
        mod.render_warm_pool_acquisition,
        mod.render_at_scale_contention,
        mod.render_cluster_saturation,
        mod.render_provisioning_rate_sweep,
        mod.render_session_turnover,
        mod.render_suspend_latency,
        mod.render_density_detail,
        mod.render_density_bars,
        mod.render_vcpu_footprint,
        mod.render_storage_config,
        mod.render_measurement_path_diagram,
        mod.render_recipe,
        mod.render_trend,
        mod.check_render_downgrade,
        mod.render_stale_banner,
        mod.resolve_default_as_of,
    )


(render_matrix, render_core_metrics_legend,
 render_north_star_caption, render_known_anomalies_table, render_known_anomalies_detail,
 render_operating_envelope, render_what_this_means,
 render_burst_corroboration, render_warm_bind_decomposition, render_bind_exec_pie,
 render_cold_bind_decomposition,
 render_warm_vs_cold, render_scale_proof, render_cluster_scale, render_stepup,
 render_cost_methodology, render_kata_activation, render_concurrent_burst,
 render_warm_pool_acquisition,
 render_at_scale_contention, render_cluster_saturation, render_provisioning_rate_sweep,
 render_session_turnover, render_suspend_latency, render_density_detail, render_density_bars,
 render_vcpu_footprint,
 render_storage_config, render_measurement_path_diagram, render_recipe, render_trend,
 check_render_downgrade,
 render_stale_banner, resolve_default_as_of) = _load_render()


def _env_flag(name):
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes", "on")

# Build-over-build throughput history (#3918/hb#439), relative to the repo root. The page
# renders only the per-product latest.json snapshot, so it can show today's COUNT but not the
# trajectory alex's #1 directive asks for. This file (sole-writer: render.accrue_history, one
# upsert-by-digest row per distinct controller build) carries that trajectory; the trend table
# is appended after the per-product loop. Absent/empty ⇒ no trend section (graceful
# degradation), so the page never half-renders.
_HISTORY_REL = "sandbox/results/history.jsonl"

# Product -> results path, relative to the repo root (parent of render/).
# The PUBLIC customer page is SANDBOX-ONLY (alex 2026-06-28): substrate demotes from a
# co-equal published table to an INTERNAL data-engine — its harness + schema-validated
# results/latest.json stay in-tree (and the cross-contract guard still validates the
# substrate emitter↔render contract against them), but they are NOT rendered to the
# public README. Re-adding the substrate tuple here is the single switch to re-publish it.
_PRODUCTS = (
    ("sandbox", "sandbox/results/latest.json"),
)

# Optional companion artifact for the sandbox matrix: the sandbox-kata product's results,
# measured in a SEPARATE run on the kata node pool (`run --product sandbox-kata` writes its
# own latest.json by construction — harness/scenario_map.py — so it can never overwrite the
# gVisor artifact). When present it fills the Kata + microVM rows of the ONE sandbox matrix
# via render_matrix(results, kata_results=...); it is deliberately NOT a _PRODUCTS entry —
# that would render a duplicate full matrix + conditional blocks instead of merging rows.
# Absent file ⇒ kata rows render pending (graceful degradation, README unchanged).
_KATA_RESULTS_REL = "sandbox-kata/results/latest.json"

# #4164 storage-config axis: dated per-fire provenance records live in sandbox/records/ (the
# schema-validated provenance units, NOT rendered output). We pick the newest by the record's
# own `measured_at` and hand the whole dict to render_storage_config, which fail-closes on a
# missing/invalid date or values. Absent glob ⇒ None ⇒ the section is INERT (omitted), so this
# is a no-op on today's page until a controlled fire lands a record (graceful degradation).
_STORAGE_CONFIG_GLOB = "sandbox/records/storage-config-*.json"


def _load_storage_config(root):
    """Newest sandbox/records/storage-config-*.json by its `measured_at` instant, as a dict;
    None when no record exists or none carries a usable date. Kept lenient here (the render is
    the closed-schema gate) — we only need a well-enough-formed date to order candidates."""
    candidates = []
    for path in glob.glob(os.path.join(root, _STORAGE_CONFIG_GLOB)):
        try:
            with open(path) as fh:
                rec = json.load(fh)
        except (OSError, ValueError):
            continue
        if isinstance(rec, dict) and isinstance(rec.get("measured_at"), str):
            candidates.append((rec["measured_at"], rec))
    if not candidates:
        return None
    # Lexicographic sort == chronological only while every record uses the same offset form
    # (the single controlled writer emits a `Z`-suffixed instant). A future `+00:00`-form
    # record would sort differently than its true chronology — revisit (parse to a datetime)
    # if the writer ever emits mixed offset forms.
    candidates.sort(key=lambda c: c[0])
    return candidates[-1][1]

# Fixed, reviewed-once customer preamble. No measured numbers here — every number on the
# page comes from render_product, so this constant carries zero PII risk.
_PREAMBLE = """\
# Honest benchmarks — GKE agent sandbox

**How fast can your agent get a sandbox that has actually run its first instruction?** That is the
only question this page answers. The metric is **TTFE (Time-To-First-Instruction)** — the wall-clock
from "create this sandbox" to "it ran my first instruction and returned a result." Not pod-Ready (a
pod can look ready seconds before it can run your code) — the real wait.

**North Star:** a warm sandbox with **TTFE p95 under 1s** — the bar the caption under the matrix
grades each runtime against (a stricter **0.5s stretch bar** is graded on the same line). The **scale
target** is to hold **sub-1s at 300+ creations/sec**, on a stock GKE cluster you can provision
yourself.

Two runtimes, two isolation trade-offs:
- **gVisor** — a user-space kernel intercepting syscalls; near-container speed, strong isolation.
- **Kata** — each sandbox in its own tiny VM; hardware-grade isolation, higher activation cost.

Every number below is **machine-rendered from a real harness run and reproducible** — no cell is
typed by hand, and each is a **floor, not a ceiling** (what a *vanilla* OSS build delivers today;
a bigger pool or denser nodes should beat it). Reproduce the whole page from a GKE cluster in
three commands (cluster setup — a gVisor/Kata node pool — is in
[`recipe/REPRODUCE.md`](recipe/REPRODUCE.md)):

```bash
bash recipe/install-controller-from-main.sh        # 1. the OSS controller, built from upstream main
python3 -m harness.run                             # 2. run the suite -> sandbox/results/latest.json
python3 -m render.generate && git diff README.md   # 3. re-render this page + diff the result
```

First run `pip install -r harness/requirements.txt`; the gVisor/Kata rows need a matching GKE node
pool — full recipe in [`recipe/REPRODUCE.md`](recipe/REPRODUCE.md), deep-dive tables in
[DETAILS.md](DETAILS.md). Cells shown as *pending* link to
[WORK_IN_PROGRESS.md](WORK_IN_PROGRESS.md) for their reason class; the upstream half of each
blocker — diagnosis plus file-ready patches and comments — is hand-maintained in
[UPSTREAM_BLOCKERS.md](UPSTREAM_BLOCKERS.md).
"""

# Deep-dive appendix header. Same no-measured-numbers-here rule as _PREAMBLE: every
# number in DETAILS.md comes from a render function, so this constant carries zero PII risk.
_DETAILS_PREAMBLE = """\
# Honest benchmarks — deep-dive appendix

The corroboration and decomposition tables behind the headline page
([README.md](README.md)) — plus the plain-English **What this means for you** guidance
on picking a runtime and sizing a warm pool. Same rule: **every number is machine-rendered
from a real harness run — nothing here is typed by hand.** Start with the headline page;
come here when you want the guidance or to see the working.
"""

# hb#488 numbers-first slice-1: the one-line pointer left on the headline page where the
# "What this means for you" interpretation block used to render inline (now relocated to the
# deep-dive appendix via build_details). Static prose — no measured number — so it lives as a
# constant, same as _PREAMBLE / _DETAILS_PREAMBLE. The anchor is GitHub's auto-slug of the
# "## What this means for you" heading emitted by render_what_this_means.
_WHAT_THIS_MEANS_POINTER = """\
**What do these numbers mean for you?** Plain-English guidance — picking a runtime, sizing a
warm pool, what wait to budget, and why a `pending` cell is unmeasured-not-bad — is in the
deep-dive appendix, [DETAILS.md](DETAILS.md#what-this-means-for-you).
"""


def _repo_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_history(root):
    """Read sandbox/results/history.jsonl into a list of dicts (malformed lines dropped); [] if absent.

    render.render_trend re-validates every row through the closed schema, so a malformed line
    that survives JSON parsing here is still dropped at render — this is parse-only.
    """
    path = os.path.join(root, _HISTORY_REL)
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return rows


def build_readme(root=None):
    """Return the full README text: preamble + 9-col Core Metrics matrix + TTFE corroboration + warm-vs-cold + Scale Proof.

    For each present product we render the closed-schema Core Metrics matrix (render_matrix),
    then — when the #3954 burst-create exec fields are present — the TTFE Corroboration block
    (render_burst_corroboration; INERT/omitted otherwise), then — when a warm_vs_cold object is
    present — the Warm-vs-Cold Speedup block (render_warm_vs_cold; INERT/omitted otherwise), and,
    when a scale_proof object is present, the Scale Proof (Linearity Check) table.
    """
    root = root or _repo_root()
    kata_results = None
    kata_path = os.path.join(root, _KATA_RESULTS_REL)
    if os.path.exists(kata_path):
        with open(kata_path) as fh:
            kata_results = json.load(fh)
    sections = [_PREAMBLE.rstrip()]
    # WS3 (epic #6669): collect each published product's (name, results) so the page-level
    # freshness self-declaration (render_stale_banner) can be computed over ALL of them and
    # inserted at the top, after the loop knows the full published set.
    published = []
    for product, rel in _PRODUCTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            results = json.load(fh)
        published.append((product, results))
        kr = kata_results if product == "sandbox" else None
        # hb home-page slim: the home page carries the matrix + a compact `***`-free cell key
        # (include_legend=False); the full glossary + `***` caveat block relocates to DETAILS
        # (render_core_metrics_legend), keeping the home page to key measurements only.
        sections.append(render_matrix(results, kata_results=kr, include_legend=False).rstrip())
        # hb#227 (GOAL-2.1, DROP-2): the former "How close to the North Star?" + "Stretch bar"
        # scorecards fold to two one-line measured-verdict captions placed directly UNDER the
        # Core Metrics matrix (render_north_star_caption). Same _north_star_rows source +
        # _p95_verdict grading, so the per-runtime verdicts are byte-identical to the retired
        # scorecard; derived entirely from the matrix's already-emitted warm-hit p95 (zero
        # emit-key change; the locked schema contract untouched).
        north_star = render_north_star_caption(results, kata_results=kr)
        if north_star.strip():
            sections.append(north_star.rstrip())
        # WS1 (epic #6669): the 6 standalone anomaly banners (Scenario FAIL, warm-slower-than-
        # cold, warm/cold separation below gate, regime note, refresh cadence, concurrent-burst
        # regime) that used to render inline here now collapse into one compact "is anything
        # currently wrong?" table with live ⚠️/✅ markers linking to DETAILS.md for the prose.
        known_anomalies = render_known_anomalies_table(results, kata_results=kr)
        if known_anomalies.strip():
            sections.append(known_anomalies.rstrip())
        # hb#488 numbers-first slice-1 (alex 2026-07-26): the plain-English "What this means
        # for you" interpretation prose — reader guidance, not a source-of-truth number — moves
        # off the headline page into the deep-dive appendix (build_details), leaving only a
        # one-line pointer here. The headline page keeps its measured numbers (matrix, north-star
        # captions, operating envelope, scale) + short explanations; the interpretive essay is a
        # click away. Same relocation precedent as render_core_metrics_legend / density → DETAILS.
        sections.append(_WHAT_THIS_MEANS_POINTER.rstrip())
        sections.append(render_operating_envelope(
            results, heading="### What wait should I budget?").rstrip())
        # hb#134: Scale-Proof + Concurrent-Burst + Saturation + at-scale Contention merge into ONE
        # user-facing "Does it hold at cluster scale?" section (render_cluster_scale demotes each
        # to a ### sub-block, including the honest over-subscription retraction as the 4th).
        cluster_scale = render_cluster_scale(results)
        if cluster_scale.strip():
            sections.append(cluster_scale.rstrip())
        stepup = render_stepup(results)  # INERT today; standalone ## when a stepup object emits
        if stepup.strip():
            sections.append(stepup.rstrip())
    # #3918/hb#439: the build-over-build throughput-COUNT trend, sourced from the sole-writer
    # accrual store (render.accrue_history), appended once after the per-product loop — same
    # graceful-degradation contract as the rest of this function: an absent/empty history
    # renders no section rather than a blank or a guess.
    # Pass the newest sandbox fire so render_trend can disclose a measured-but-unanchored COUNT
    # (trend-vs-latest divergence guard) instead of rendering a stale trend as if current.
    sandbox_latest = None
    sandbox_latest_rel = next((rel for p, rel in _PRODUCTS if p == "sandbox"), None)
    if sandbox_latest_rel:
        sandbox_latest_path = os.path.join(root, sandbox_latest_rel)
        if os.path.exists(sandbox_latest_path):
            with open(sandbox_latest_path) as fh:
                sandbox_latest = json.load(fh)
    trend = render_trend(_load_history(root), latest_results=sandbox_latest)
    if trend.strip():
        sections.append(trend.rstrip())
    # #4164 / hb#132: "Which storage class should you pick?" is a single sandbox-wide guidance
    # section (customer-facing storage-config axis), sourced from the newest
    # sandbox/records/storage-config-*.json — so it renders ONCE after the per-product loop, placed
    # after "Does it hold at cluster scale?" and before "Reproduce it". Data-keyed degradation:
    # renders NOTHING until a record carries a valid measured_at + at least one in-enum class.
    storage_config = render_storage_config(_load_storage_config(root))
    if storage_config.strip():
        sections.append(storage_config.rstrip())
    # WS2 (epic #6669): the "How is TTFE measured?" mermaid flowchart is product-agnostic
    # architecture-shape (no measured numbers, same posture as render_recipe below), so it
    # renders ONCE after the per-product loop — placed right before the recipe so a reader who
    # wants to reproduce the numbers sees how they were captured first.
    sections.append(render_measurement_path_diagram().rstrip())
    # #4021: the Reproducibility Recipe is product-agnostic architecture prose, so it renders
    # ONCE after the per-product loop — the preamble forward-refs "the recipe at the bottom".
    sections.append(render_recipe().rstrip())
    # WS3 (epic #6669): the freshness self-declaration renders at the TOP (right after the
    # preamble H1/intro), so a customer sees a STALE/UNVERIFIED warning before any number. Empty
    # string (every product fresh) inserts nothing — freshness is the silent, expected state.
    stale_banner = render_stale_banner(published, as_of=resolve_default_as_of())
    if stale_banner:
        sections.insert(1, stale_banner)
    return "\n\n".join(sections) + "\n"


def build_details(root=None):
    """Return the deep-dive appendix (DETAILS.md): corroboration + decomposition tables.

    hb#134 page-friendliness split: the headline README carries the answer a non-infra
    reader needs (matrix + operating envelope + scale + burst); the working behind those
    numbers — burst-create corroboration, the bind-vs-exec decomposition (warm + cold),
    the full warm-vs-cold leg table (only its punchline stays on the headline page),
    the Kata pod-Ready table, the warm-pool acquisition breakdown, and the per-runtime
    Max-Density table (relocated off the headline matrix in the same pass) — moves here so
    the front page stays scannable. Same closed-schema render path as build_readme: each
    block is INERT (returns "") unless its required fields are present, so DETAILS degrades
    to an honest skeleton rather than a blank or a guess.
    """
    root = root or _repo_root()
    kata_results = None
    kata_path = os.path.join(root, _KATA_RESULTS_REL)
    if os.path.exists(kata_path):
        with open(kata_path) as fh:
            kata_results = json.load(fh)
    sections = [_DETAILS_PREAMBLE.rstrip()]
    for product, rel in _PRODUCTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            results = json.load(fh)
        kr = kata_results if product == "sandbox" else None
        # WS1 (epic #6669): DETAILS-side counterpart to the README "Known anomalies" table —
        # placed first in the per-product detail sequence so the anchors it emits
        # (#scenario-fail, #warm-slower-than-cold, etc.) are near the top of the page the
        # README's table links into.
        known_anomalies_detail = render_known_anomalies_detail(results, kata_results=kr)
        if known_anomalies_detail.strip():
            sections.append(known_anomalies_detail.rstrip())
        for renderer in (
            render_burst_corroboration,
            render_warm_bind_decomposition,
            render_bind_exec_pie,
            render_cold_bind_decomposition,
            render_warm_vs_cold,
            render_kata_activation,
            render_warm_pool_acquisition,
        ):
            block = renderer(results)
            if block.strip():
                sections.append(block.rstrip())
        # Max-Density relocated here from the headline matrix (hb#134); it and the blocks
        # below reuse the `kr` set at the top of the loop (kata_results for sandbox only).
        # HB1 (alex 2026-07-25): the full cell-decoding glossary + published-with-caveat
        # block moved off the headline matrix to here; the README matrix carries only a
        # compact "Reading the cells" pointer back to this section. Byte-faithful gating:
        # the caveat block renders iff the DEFAULT-legend matrix would have shown ***.
        legend = render_core_metrics_legend(results, kata_results=kr)
        if legend.strip():
            sections.append(legend.rstrip())
        density = render_density_detail(results, kata_results=kr)
        if density.strip():
            sections.append(density.rstrip())
        # WS2 (epic #6669): visual companion to the density table above — same source, same
        # kata_results, INERT under the identical conditions. Placed immediately after the table
        # it visualizes so a reader sees the numbers and the bar chart together.
        density_bars = render_density_bars(results, kata_results=kr)
        if density_bars.strip():
            sections.append(density_bars.rstrip())
        # #3868: per-sandbox declared footprint — the reproducibility qualifier for Max Density
        # (gVisor's tiny request vs Kata's guest-sane microVM floor differ ~50x, so densities are
        # only comparable with the footprint stated). Placed next to density; same kata_results
        # source. INERT-first: renders nothing until a fire emits the provenance footprint fields.
        footprint = render_vcpu_footprint(results, kata_results=kr)
        if footprint.strip():
            sections.append(footprint.rstrip())
        # hb#134: the honest-limits RETRACTION posture stays on the headline page; only the full
        # bind/exec decomposition table + non-comparable caveat move here (detail=True).
        contention_detail = render_at_scale_contention(results, detail=True)
        if contention_detail.strip():
            sections.append(contention_detail.rstrip())
        # hb#132: the cluster-saturation ceiling keeps its headline posture on the front page (the
        # third render_cluster_scale sub-block); only the full per-node/per-cluster + bind/exec
        # decomposition table moves here (detail=True), mirroring the at_scale_contention split.
        saturation_detail = render_cluster_saturation(results, detail=True)
        if saturation_detail.strip():
            sections.append(saturation_detail.rstrip())
        # #4086: provisioning-rate ceiling — a THIRD distinct axis (offered reconcile rate vs
        # ready-convergence), not folded into the step-up Pareto or at_scale_contention.
        # DETAILS-only for now; headline promotion tracked as a follow-up.
        rate_sweep = render_provisioning_rate_sweep(results)
        if rate_sweep.strip():
            sections.append(rate_sweep.rstrip())
        # Cost-axis methodology: the headline step-up table carries a Cost ($/1k ready) column, but
        # the closed formula + honesty spine + the operator_rate-vs-list_price basis have no home on
        # the scannable front page. Deep-dive here. INERT unless the run carries a costed Pareto
        # point (no methodology for a number that isn't on the page).
        cost_meth = render_cost_methodology(results)
        if cost_meth.strip():
            sections.append(cost_meth.rstrip())
        # #3868: warm-pool session-turnover refill latency — the RECLAIM side of the agentic
        # lifecycle (the matrix + warm_pool_acquisition measure the claim side). INERT-first:
        # renders nothing until a session_turnover fire emits a measured refill median. DETAILS-only
        # for now; headline promotion tracked as a follow-up (mirrors render_provisioning_rate_sweep).
        turnover = render_session_turnover(results)
        if turnover.strip():
            sections.append(turnover.rstrip())
        # #3868: administrative-suspend latency — the cost-lever response time for reclaiming a
        # sandbox's compute (operatingMode=Suspended patch -> terminal Suspended). Carries a static
        # capability note that upstream has NO idle/auto-suspend (operatingMode is Running;Suspended
        # only). INERT-first: renders nothing until a suspend_resume fire emits a measured suspend
        # median. DETAILS-only for now; headline promotion tracked as a follow-up.
        suspend = render_suspend_latency(results)
        if suspend.strip():
            sections.append(suspend.rstrip())
        # hb#488 numbers-first slice-1 (alex 2026-07-26): the plain-English "What this means for
        # you" interpretation prose relocates off the headline page to here (README carries only
        # _WHAT_THIS_MEANS_POINTER). Placed LAST in the per-product loop so the section's own
        # "the tables above" / "matrix rows above" self-references stay accurate — all the working
        # tables render above it — with zero change to render_what_this_means' prose. The README
        # pointer targets its #what-this-means-for-you anchor, so a reader jumps straight here.
        sections.append(render_what_this_means(results, kata_results=kr).rstrip())
    return "\n\n".join(sections) + "\n"


def _render_downgrades(root, combined_text):
    """hb#550: run check_render_downgrade against every source this generate pass rendered
    (sandbox latest.json + the optional sandbox-kata companion), scoped per-source since
    each results file is one runtime's worth of scenarios. Returns finding strings; empty
    means clean."""
    findings = []
    for _product, rel in _PRODUCTS:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            results = json.load(fh)
        findings.extend(check_render_downgrade(results.get("scenarios"), combined_text))
    kata_path = os.path.join(root, _KATA_RESULTS_REL)
    if os.path.exists(kata_path):
        with open(kata_path) as fh:
            kata_results = json.load(fh)
        findings.extend(check_render_downgrade(kata_results.get("scenarios"), combined_text))
    return findings


def main(argv=None):
    root = _repo_root()
    readme = build_readme(root)
    details = build_details(root)
    # hb#550 / AGENTS.md "guard-then-fill": compute the fail-closed render-trust-downgrade
    # check against the IN-MEMORY rendered text BEFORE any file write, mirroring
    # check_cell_downgrade's posture in harness/run.py. A refusal here writes nothing at
    # all (not a partial README-written-DETAILS-refused straddle).
    downgrades = _render_downgrades(root, readme + "\n" + details)
    if downgrades:
        for line in downgrades:
            sys.stderr.write(f"generate: render-downgrade: {line}\n")
        if _env_flag("BENCH_ALLOW_RENDER_DOWNGRADE"):
            sys.stderr.write(
                f"generate: BENCH_ALLOW_RENDER_DOWNGRADE set — publishing "
                f"{len(downgrades)} downgraded render(s) anyway (deliberate downgrade)\n"
            )
        else:
            sys.stderr.write(
                f"generate: refusing to write output: {len(downgrades)} render(s) would "
                f"silently downgrade a trust surface (missing FAIL disclosure, or a "
                f"measured scenario rendering as bare `pending`). Re-fire carrying the "
                f"envs the affected scenario(s) were measured with, or set "
                f"BENCH_ALLOW_RENDER_DOWNGRADE=1 to downgrade deliberately.\n"
            )
            return 1
    out = os.path.join(root, "README.md")
    with open(out, "w") as fh:
        fh.write(readme)
    sys.stderr.write(f"generate: wrote {out} ({len(readme)} bytes)\n")
    details_out = os.path.join(root, "DETAILS.md")
    with open(details_out, "w") as fh:
        fh.write(details)
    sys.stderr.write(f"generate: wrote {details_out} ({len(details)} bytes)\n")
    # hb#166: the WORK_IN_PROGRESS.md page every pending/absent cell links to. Machine-rendered
    # from the closed pending-reason enum (wip.py), never hand-maintained — same generate-only
    # contract as README/DETAILS.
    wip = build_work_in_progress()
    wip_out = os.path.join(root, "WORK_IN_PROGRESS.md")
    with open(wip_out, "w") as fh:
        fh.write(wip)
    sys.stderr.write(f"generate: wrote {wip_out} ({len(wip)} bytes)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
